class RecordAttributes:
    asctime = "asctime"
    created = "created"
    filename = "filename"
    funcName = "funcName"
    levelname = "levelname"
    levelno = "levelno"
    lineno = "lineno"
    message = "message"
    module = "module"
    name = "name"
    pathname = "pathname"
    process = "process"
    processName = "processName"
    relativeCreated = "relativeCreated"
    thread = "thread"
    threadName = "threadName"
