from PLogging.resources.color_config import FONT_WHITE, FONT_GREEN, FONT_MAGENTA, FONT_YELLOW, FONT_RED, FONT_BLUE

COLORS = {
    "DEBUG": FONT_WHITE,
    "INFO": FONT_GREEN,
    "TRAVA_LOG": FONT_MAGENTA,
    "WARNING": FONT_YELLOW,
    "ERROR": FONT_RED,
    "CRITICAL": FONT_BLUE
}
